### ISSUE TITLE
Reset Mapbox Events

### ISSUE THREAD

**Issue by CarloC-AB** [reyemb/streamlit-plotly-mapbox-events#1]
Hi,

Is there a way to reset the mapbox events selections? I have an app where the selections you do appends to a list. You then have a reset button to empty the list, but when you interact with another component and refresh the page, the previous selection you did pop up on the list, so is there a way to just remove the previous selections when clicking on this reset button?

**Comment by reyemb** [comment]
Can you provide me with sample code? But normaly you would to something like 

```
def reset():
   list_selection = []

st.button("Resett", on_click="reset")
```

**Comment by reyemb** [comment]
Will be closed since no reply. Feel free to reopen the issue
