### ISSUE TITLE
Weird glitches when using mapbox events

### ISSUE THREAD

**Issue by HugoAndre276** [reyemb/streamlit-plotly-mapbox-events#2]
Hi! 
I'm having issues when using this module as weird glitches happen on the streamlit page.
Here is the code I'm using:
```
import streamlit as st

import pandas as pd

import plotly.express as px
from streamlit_plotly_mapbox_events import plotly_mapbox_events


d = {'lat' : [1,2,3,4],'lon' : [1,2,3,4]}
df = pd.DataFrame(data = d)

fig = px.scatter_mapbox(df, lat="lat", lon="lon", zoom=3, height=500)
fig.update_layout(mapbox_style="open-street-map")

mapbox_events = plotly_mapbox_events(
    fig,
    click_event=True,
    select_event=True,
    hover_event=False,
    relayout_event=False)

st.plotly_chart(fig)
```
![image](https://github.com/reyemb/streamlit-plotly-mapbox-events/assets/57095076/ab408ef1-162c-4833-98bc-eb48df809f5b)
_The bottom map glitches up and down and shouldn't be here in the first place_

Now with this code
```
import streamlit as st

import pandas as pd

import plotly.express as px

d = {'lat' : [1,2,3,4],'lon' : [1,2,3,4]}
df = pd.DataFrame(data = d)

fig = px.scatter_mapbox(df, lat="lat", lon="lon", zoom=3, height=500)
fig.update_layout(mapbox_style="open-street-map")

st.plotly_chart(fig)
```
![image](https://github.com/reyemb/streamlit-plotly-mapbox-events/assets/57095076/4493192a-7974-4809-87a5-94a6e980a18d)
Which is expected.

I've tried using the example code you gave but the same kind of problem arises.

Am I doing anything wrong?

I'm using conda for python 3.12.2

Thanks!

**Comment by reyemb** [comment]
Hey Hugo,

thank you for providing the detailed description. I could reproduce the error and found a fix. Currently having some troubles with uploading the new version to pypi.

I think I get it solved tomorrow or the day after tomorrow

Cheers

**Comment by reyemb** [comment]
There is a new version. I have changed the repository. You can now download & install the component using:

pip install streamlit-plotly-mapbox-events

I run your example using these lines of code and it worked smoothly for me:

```python
import streamlit as st
import plotly.express as px
import pandas as pd
from streamlit_plotly_mapbox_events import plotly_mapbox_events


st.set_page_config(layout="wide")

if 'Plotly Mapbox' not in st.session_state:
    d = {'lat' : [1,2,3,4],'lon' : [1,2,3,4]}
    df = pd.DataFrame(data = d)

    fig = px.scatter_mapbox(df, lat="lat", lon="lon", zoom=3, height=500)
    fig.update_layout(mapbox_style="open-street-map")
    st.session_state['Plotly Mapbox'] = fig

mapbox_events = plotly_mapbox_events(st.session_state['Plotly Mapbox'],click_event=True,select_event=True,hover_event=True, override_height=600)

plot_name_holder_clicked = st.empty()
plot_name_holder_selected = st.empty()
plot_name_holder_hovered = st.empty()

plot_name_holder_clicked.write(f"Clicked Point: {mapbox_events[0]}")
plot_name_holder_selected.write(f"Selected Point: {mapbox_events[1]}")
plot_name_holder_hovered.write(f"Hovered Point: {mapbox_events[2]}")
```

**Comment by HugoAndre276** [comment]
It's working perfectly, thanks a lot!
